<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.30.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="7.0.2" />
	<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.2" />
	<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
	<PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
	<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="7.0.2" />
    <PackageReference Include="System.Net.Http.Json" Version="7.0.0" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorBarcodeScanner.ZXing.JS\BlazorBarcodeScanner.ZXing.JS.csproj" />
    <ProjectReference Include="..\Fims.Common\Fims.Common.csproj" />
    <ProjectReference Include="..\Fims.Data\Fims.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\TelerikMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TelerikMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\fimsapp.svg">
      <Color>#C00CC0</Color>
      <ForegroundFile>Resources\AppIcon\appiconfg.svg</ForegroundFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\TelerikMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TelerikMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
